server:
  port: 9003

spring:
  application:
    name: ORDER-MANAGEMENT
  datasource:
    url: jdbc:mysql://localhost:3306/ms_corporate
    username: root
    password: 1008
  zipkin:
    base-url: http://127.0.0.1:9411/
  jpa:
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


